Fix update reference for COPY_IN objects
beehive-lab/TornadoVM pull request #100
Opened 2021-04-29 22:43 UTC by gigiblender

#### Description

This PR contains the following changes:
- Clean the Local/GlobalObjectState objects. Remove the concept of `owner` device.
- Fix TaskSchedule::updateReference for objects that are copied via a COPY_IN bytecode.
- Expand profiling information for sync operations and differentiate between dispatch kernel and data transfer times.

#### Problem description

The problems fixed in this PR are the following:
1) When `TaskSchedule::updateReference` is called on a variable that is copied in (via a `COPY_IN` bytecode), the runtime thinks that the data is already on the device and will not perform any update. This is fixed by invalidating the object state and updating the necessary datastructures. (Check `TornadoExecutionContext::replaceObjectState`)

2) Expand the profiling information to include times for `sync` operations; Include call stack writing in the reported COPY_IN times. Split `DISPATCH_TIME` into `TOTAL_DISPATCH_DATA_TRANSFERS_TIME` and `TOTAL_DISPATCH_KERNEL_TIME`.

3) Remove the GridTask from the `TornadoVM` constructor. Instead, update the `GridTask` of the `TornadoVM` object separately, since the same `TornadoVM` object might be used with different `GridTask`s

#### Backend/s tested

- [X] OpenCL
- [X] PTX

#### OS tested

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If possible, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

Running the unit tests should cover this PR. 
For the update reference fix, check `Resize::testUpdateReferenceCopyIn`

2021-05-03 08:00 UTC, jjfumero commented
Please, update the PR description with the new unittests introduced in this patch.

2021-05-03 08:05 UTC, jjfumero requested changes

2021-05-03 08:05 UTC, jjfumero commented on runtime/src/main/java/uk/ac/manchester/tornado/runtime/profiler/TimeProfiler.java
> +    public static String NO_TASK_NAME = "noTask";
Add Java-doc why this taskName is neded. Also, you can relate to the open issue we have to discuss this.

2021-05-05 15:08 UTC, stratika requested changes
The only part that I would suggest to update is the comment in `TornadoTaskSchedule.java` in order to be more clear.

2021-05-05 20:26 UTC, gigiblender commented on drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
> +        int kernelLaunchEvent = stream.enqueueKernelLaunch(module, writePTXStackOnDevice((PTXCallStack) stack, module.metaData), gridDimension, blockDimension);
Yes, you're right. I should get a merge conflict once we merge that

2021-05-06 07:26 UTC, stratika approved these changes

2021-05-10 12:22 UTC, merged