Fix 2D arrays for OpenCL
beehive-lab/TornadoVM pull request #115
Opened 2021-05-27 15:41 UTC by gigiblender

#### Description

In the OpenCL backend, there was support for 2D arrays added at some point but we no further maintained it. This PR fixes 2D arrays and adds some unit tests for that.

#### Problem description

The issue is that `getBufferOffset` has a different implementation in `OCLMultiDimArrayWrapper`
```
    @Override
    public long getBufferOffset() {
        return tableWrapper.getBufferOffset();
    }
```

The PTX backend has no support for 2D arrays.

#### Backend/s tested

- [X] OpenCL
- [ ] PTX

#### OS tested

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If possible, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

Run the unit tests.
```
tornado-test.py --printKernel --verbose uk.ac.manchester.tornado.unittests.arrays.TestMatrix
```

2021-05-31 15:16 UTC, jjfumero requested changes

2021-05-31 15:16 UTC, jjfumero commented on assembly/src/bin/tornado-test.py
> +    TestEntry("uk.ac.manchester.tornado.unittests.arrays.TestMatrix"),
Append these tests in the TestMatrices

2021-05-31 15:16 UTC, jjfumero commented on unittests/src/main/java/uk/ac/manchester/tornado/unittests/arrays/TestMatrix.java
> +    public static void testAdd(long[][] matrix) {
Move this tests into `TestMatrices`

2021-06-01 05:11 UTC, jjfumero approved these changes

2021-06-01 09:05 UTC, stratika approved these changes

2021-06-01 09:50 UTC, merged