[docs] Windows 10/11 installation updated
beehive-lab/TornadoVM pull request #242
Opened 2023-04-24 07:34 UTC by jjfumero

This PR updates the documentation, hosted in https://tornadovm.readthedocs.io/en/latest/ with the following changes:

1. Update the installation instructions for Windows 10/11 with MSys2
2. Fixed typos on the `unsupported` page. 

The new version of the documentation will be rendered automatically with this PR.

2023-04-24 07:42 UTC, mairooni requested changes

2023-04-24 07:42 UTC, mairooni commented on docs/source/installation.rst
> +The only thing to note is that GPU driver you are currently using should be of the same or higher version than the one shipped with CUDA Toolkit.
Instead of writing "note" again, we could say something like "It is important to make sure that the GPU driver..."

2023-04-24 07:42 UTC, mairooni commented on docs/source/installation.rst
> +Thus, if you have existing driver make sure that it's version is same or higher, otherwise update GPU driver during toolkit installation.
it's -> its

2023-04-26 07:25 UTC, kotselidis commented on docs/source/installation.rst
> +Thus, if you have the driver already installed, make sure that the version required by the CUDA SDK is same or higher, otherwise update GPU driver during toolkit installation.
"the GPU driver"

2023-04-26 07:26 UTC, kotselidis commented on docs/source/installation.rst
> +Note, that NSight, BLAST libs and Visual Studio integration are irrelevant for TornadoVM builds, you need just SDK - so you may skip installing them.
"you just need the SDK"

2023-04-26 07:27 UTC, kotselidis commented on docs/source/installation.rst
> +3. Compile TornadoVM
Before it was 5 and not it is 3? is it because of the PR or wrong numbering?

2023-04-26 07:33 UTC, jjfumero commented
All fixes done

2023-04-26 07:42 UTC, kotselidis approved these changes

2023-04-26 07:44 UTC, merged