[docs] Installation for Windows docs improved
beehive-lab/TornadoVM pull request #413
Opened 2024-05-10 10:12 UTC by jjfumero

#### Description

Improve the documentation for the installation of TornadoVM on Windows 10/11

#### Problem description

n/ a.

#### Backend/s tested

Mark the backends affected by this PR.

- [X] OpenCL
- [X] PTX
- [X] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [ ] Linux
- [ ] OSx
- [X] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

Link to the documentation.

2024-05-10 10:36 UTC, mairooni requested changes

2024-05-10 10:36 UTC, mairooni commented on docs/source/installation.rst
> +**[DISCLAIMER] Please, notice that, although TornadoVM can run on Windows 10/11, it is still experimental.**
note instead of notice

2024-05-10 12:05 UTC, stratika requested changes

2024-05-10 12:05 UTC, stratika commented on docs/source/installation.rst
> +   # explore accelerator reachable from TornadoVM
```suggestion

   # list the accelerator devices that are reachable from TornadoVM
```

2024-05-10 12:05 UTC, stratika commented on docs/source/installation.rst
> +   # explore accelerator reachable from TornadoVM
I added a space line in line 622, because the code snippet (beneath it) is not shown.

2024-05-13 07:40 UTC, jjfumero commented on docs/source/installation.rst
> +   python bin\tornadovm-installer --jdk jdk21 --backend=opencl
I think in the feature we should only allow to install through the installer script. For now, let's maintain the `nmake` approach as well. I will change this.

2024-05-13 07:48 UTC, jjfumero commented
All comments resolved.

2024-05-13 08:07 UTC, stratika approved these changes

2024-05-13 08:37 UTC, mairooni approved these changes

2024-05-13 08:43 UTC, merged