Documentation Updated: Installation, landing page and resources
beehive-lab/TornadoVM pull request #429
Opened 2024-05-20 08:10 UTC by jjfumero

#### Description

This PR updates the documentation with special attention to the installation steps for all supported OS.

#### Problem description

n/ a.

#### Backend/s tested

Mark the backends affected by this PR.

- [ ] OpenCL
- [ ] PTX
- [ ] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [ ] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

```bash
make docs
google-chrome docs/build/html/index.html
```

2024-05-20 09:45 UTC, mairooni requested changes

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
> +Installer Script
Suggestion: Installer Script -> Installation Script

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
> +Installattion for Windows 10/11
Installattion -> Installation

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
> +The installer script downloads the following dependencies:
If you implement the suggestion above, change this to the "installation script"

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
>  This installation script has been tested on Linux, macOS and Windows.
If you don't apply the suggestion, consider changing the "installation script" to "installer script" for consistency.

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
> +And TornadoVM is readyt to be used. If you want to recompile with a different backend:
readyt -> ready

2024-05-20 09:45 UTC, mairooni commented on docs/source/installation.rst
> +Installattion for ARM Mali GPUs
Installattion -> Installation

2024-05-20 09:56 UTC, mairooni approved these changes

2024-05-22 09:01 UTC, stratika requested changes

2024-05-22 09:09 UTC, jjfumero commented on docs/source/resources.rst
> +-  Adam Bien Podcast with Juan Fumero: `FPGAs, GPUs or Data Science with Java <https://airhacks.fm/#episode_282>`_.
I just fixed it.

2024-05-22 09:32 UTC, stratika approved these changes

2024-05-22 09:32 UTC, merged