Add documentation to run unit-test through Intellij
beehive-lab/TornadoVM pull request #445
Opened 2024-06-07 08:01 UTC by mikepapadim

#### Description

Add entry to documentation to explain the cofiguration for running unit-tests through Intellij.

#### Backend/s tested

Mark the backends affected by this PR.

- [ ] OpenCL
- [ ] PTX
- [ ] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [ ] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [ ] No

----------------------------------------------------------------------------

2024-06-07 08:29 UTC, stratika requested changes

2024-06-07 08:29 UTC, stratika commented on docs/source/ide-integration.rst
> +result a successful build for TornadoVM.
```suggestion
result in a successful build for TornadoVM.
```

2024-06-07 08:29 UTC, stratika commented on docs/source/ide-integration.rst
> +   -  The Project Language Level is using the same java version (e.g. Java 21 (Preview).
Let's update `line 67` with Java 21, for consistency

2024-06-07 08:29 UTC, stratika commented on docs/source/ide-integration.rst
> -   /PATH_TO_JDK/jdk1.8.0_131/bin/java
`Lines 69-71` the `right click > create tornadovm [package]` does not to exist any more. Can we please update also those instructions?

2024-06-07 08:29 UTC, stratika commented on docs/source/ide-integration.rst
> -   -server -XX:-UseJVMCIClassLoader -XX:-UseCompressedOops -Djava.ext.dirs=/home/michalis/Tornado/tornado/bin/sdk/share/java/tornado -Djava.library.path=/home/michalis/Tornado/tornado/bin/sdk/lib -Dt
`Lines 76-90` please update the `cmake` version and the `jdk-8` profile to match the current version/profiles.

2024-06-07 08:46 UTC, jjfumero requested changes

2024-07-25 10:09 UTC, andrii0lomakin commented on docs/source/ide-integration.rst
> +You need to copy from ``-server`` to end.
If I had gotten it correctly, this option ` -XX:-UseCompressedOops` would not have been needed after migration to Java FF API.

2024-07-25 10:26 UTC, jjfumero commented on docs/source/ide-integration.rst
> +You need to copy from ``-server`` to end.
Exactly, there is no need for this flag any more.

2024-07-25 14:31 UTC, jjfumero commented
@mikepapadim , is this PR still going?

2024-07-25 15:25 UTC, mikepapadim commented
> @mikepapadim , is this PR still going?

let me do another pass, so we can merge it

2024-10-29 10:43 UTC, stratika commented
I will close this PR, after merging PRs #582 #583

2024-10-29 10:43 UTC, closed without merging