[feat] Query Memory Consumption and expanded profiler with memory consumption
beehive-lab/TornadoVM pull request #448
Opened 2024-06-11 14:17 UTC by jjfumero

#### Description

This PR expands the profiler and the TornadoVM Execution Plan API to obtain the current memory consumption per task-graph, total number of bytes transferred to the device back and forth per execution plan, and the total memory usage.  This feature is requested from the GAIA project. 

a) `getTotalBytesTransferred`

This expands the profiler to obtain the total number of bytes transferred in every execution plan launch. The number of bytes transferred depends on READ_ONLY, WRITE_ONLY and READ_WRITE data buffers. 

```java
 try (TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph)) {
            TornadoExecutionResult executionResult = executionPlan.execute();
            long totalBytesTransferred = executionResult.getProfilerResult().getTotalBytesTransferred();
            long copyInBytes = executionResult.getProfilerResult().getTotalBytesCopyIn();
            long copyOutBytes = executionResult.getProfilerResult().getTotalBytesCopyOut();
            assertEquals(copyInBytes + copyOutBytes, totalBytesTransferred);
        }
```

b)  `getTotalDeviceMemoryUsage` 

The total device memory usage registers all allocations needed to run an execution plan. This value can be queried using the TornadoVM profiler. 

```java
try (TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph)) {
            TornadoExecutionResult executionResult = executionPlan.execute();
            long totalMemoryUsedInBytes = executionResult.getProfilerResult().getTotalDeviceMemoryUsage();

            // 3 Arrays
            final long sizeAllocated = a.getNumBytesOfSegmentWithHeader() * 3;
            assertEquals(sizeAllocated, totalMemoryUsedInBytes);

        }
```

c) `getCurrentMemoryUsage`

Value to query at the execution plan level, to obtain the actual memory usage at any point during execution. 

```java
try (TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph)) {
            executionPlan.execute();
            long currentMemoryUsageInBytes = executionPlan.getCurrentMemoryUsage();
            final long sizeAllocated = a.getNumBytesOfSegmentWithHeader() * 3;
            assertEquals(sizeAllocated, currentMemoryUsageInBytes);
        }
```

#### Problem description

n/ a.

#### Backend/s tested

Mark the backends affected by this PR.

- [X] OpenCL
- [X] PTX
- [X] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

```bash
make BACKEND=opencl
tornado-test --enableProfiler console -V uk.ac.manchester.tornado.unittests.memory.MemoryConsumptionTest

make BACKEND=ptx
tornado-test --enableProfiler console -V uk.ac.manchester.tornado.unittests.memory.MemoryConsumptionTest

make BACKEND=spirv
tornado-test --enableProfiler console -V uk.ac.manchester.tornado.unittests.memory.MemoryConsumptionTest
```

2024-06-11 16:06 UTC, mairooni approved these changes

2024-06-12 07:04 UTC, stratika requested changes

2024-06-12 07:04 UTC, stratika commented on tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
> +        long memoryRegionDellocated = 0;
refactor the variable to `deallocatedSpace` to keep consistency with the `allocate` method. Also, let's use the same variable names across all backends:
`PTXTornadoDevice`, `SPIRVTornadoDevice`.

2024-06-12 07:04 UTC, stratika commented on tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
> +        long spaceDeallocated = 0;
Refactor variable to `deallocatedSpace`

2024-06-12 07:04 UTC, stratika commented on tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
> +        long spaceDeallocated = 0;
Refactor variable to `deallocatedSpace`

2024-06-12 10:01 UTC, jjfumero commented on tornado-assembly/src/bin/tornado-test
> +    TestEntry("uk.ac.manchester.tornado.unittests.memory.TestStressDeviceMemory"),
Yes

2024-06-12 10:06 UTC, jjfumero commented
All comments applied

2024-06-12 10:15 UTC, stratika approved these changes
Thanks @jjfumero. LGTM

2024-06-12 10:17 UTC, merged