Fix non-JNI types in PTXStream.cpp; fix posix_memalign usage in OCLCo…
beehive-lab/TornadoVM pull request #46
Opened 2021-01-16 13:51 UTC by vsilaev

1. Root `pom.xml` is modified to use Unix `cmake.generator` on Windows (MingW64 GCC build is assumed)
2.  `CMakeLists.txt` is modified to replace `-rdynamic` with `-export-dynamic` flag (recognizable by MingW64 GCC) and to exclude any prefixes generated by MingW64 to target DLL names
3. In `opencl-jni` the file `OCLContext.cpp` is modified to use `_aligned_malloc` function instead of Unix-only `posix_memalign`
4. In `ptx-jni` the file `PTXStream.cpp` is fixed to use correct JNI types like `jint`, `jlong`, `jdouble` instead of native C types `int`, `long`, `double`
5. `tornado` in `assemby` now has no unused environment variable `EXTERNAL_DIRS` , otherwise external Java library path is set incorrectly on Windows

Signed-off-by: vsilaev <vsilaev@gmail.com>

2021-01-18 08:25 UTC, jjfumero commented
Thank you @vsilaev. I will test it on Linux and on the FPGAs. I need to check the alignment on the Xilinx and Altera FPGAs. 

What to expect from us? I can work on this after 31st Jan. So you can expect feedback/comments from there. 

Thanks

2021-01-28 12:01 UTC, stratika requested changes

2021-01-28 12:38 UTC, jjfumero commented
This PR should only push the Windows support. Please, do not mix Windows support with the `async/await` proposal.

2021-01-28 13:24 UTC, stratika commented
In addition, it would be good to resolve the `make clean` in Windows, instead of deleting manually the `bin/bin`, `bin/sdk` and `dist` folders.

And include a documentation file in `assembly/src/docs` that will be a guideline of all the steps mentioned in the issue #16 for executing TornadoVM in Windows.

2021-01-29 16:51 UTC, vsilaev commented
My apologizes - I played too hard with original branch for pull request and now I can't revert commits.
It was simpler to re-start over (I have a separate PATCH files anyway) and create new pull request - https://github.com/beehive-lab/TornadoVM/pull/54

It contains same changes from my side with all your feedback applied.

2021-02-04 10:00 UTC, closed without merging