Extend type support for 3D matrices
beehive-lab/TornadoVM pull request #576
Opened 2024-10-07 12:40 UTC by mairooni

#### Description

This PR provides support for int, double, long and short 3d arrays by creating new matrix classes.

#### Backend/s tested

Mark the backends affected by this PR.

- [x] OpenCL
- [x] PTX
- [x] SPIRV

#### OS tested

Mark the OS where this PR is tested.

- [x] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If it is applicable, check your changes on FPGAs.

- [ ] Yes
- [x] No

#### How to test the new patch?

The `TestMatrixTypes` unittest has been extended with tests for the new 3d types. 
To test run: 
`tornado-test -V uk.ac.manchester.tornado.unittests.matrices.TestMatrixTypes`

2024-10-08 12:15 UTC, jjfumero requested changes

2024-10-08 12:15 UTC, jjfumero commented on tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/utils/LongOps.java
> +package uk.ac.manchester.tornado.api.types.utils;
Add the license

2024-10-08 12:19 UTC, jjfumero commented
Thanks @mairooni . It works for all supported backends. Apart from the missing license header, LGTM

2024-10-09 08:38 UTC, jjfumero approved these changes

2024-10-10 10:39 UTC, stratika approved these changes
LGTM, I will keep a note to extend the TornadoInsight plugin for the new API types.

2024-10-10 10:44 UTC, merged