Fix/vector api
beehive-lab/TornadoVM pull request #68
Opened 2021-02-25 14:00 UTC by mikepapadim

#### Description
This bug provides a fix for issue #60.
Also, provides minor refactoring by removing deprecated `toString()` methods in the VectorAPI.

#### Problem description

The issue is due to incorrect formating on  `Vector` objects available for various lengths (i.e, 2,3,4, and 8).
Previously, the `toString()` method will cause the following error:

```
Exception in thread "main" java.util.IllegalFormatConversionException: f != uk.ac.manchester.tornado.api.collections.types.Float3
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2806)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2753)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at uk.ac.manchester.tornado.api.collections.types.VectorFloat3.toString(VectorFloat3.java:175)
	at uk.ac.manchester.tornado.api.collections.types.VectorFloat3.toString(VectorFloat3.java:193)
	at uk.ac.manchester.tornado.examples.vectors.VectorAddTest.main(VectorAddTest.java:41)
```

#### Backend/s tested

- [x] OpenCL
- [x] PTX

#### OS tested

- [x] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If possible, check your changes on FPGAs.

- [ ] Yes
- [x] No

#### How to test the new patch?

2021-02-25 14:46 UTC, stratika approved these changes
Thanks @mikepapadim, this seems to fix the issue with the Exception.

I confirm it works also in Mac OSx.

2021-03-01 08:37 UTC, jjfumero requested changes

2021-03-01 08:37 UTC, jjfumero commented on tornado-api/src/main/java/uk/ac/manchester/tornado/api/collections/types/ImageFloat4.java
> +            result += "\n" + toString(FloatOps.FMT_3);
Should not be this `FloatOps.FMT_4`?

2021-03-01 08:42 UTC, jjfumero commented
I confirm this patch works

2021-03-02 08:35 UTC, jjfumero commented on tornado-api/src/main/java/uk/ac/manchester/tornado/api/collections/types/ImageFloat4.java
> +            result += "\n" + toString(FloatOps.FMT_3);
@mikepapadim , when you get the time, please take a look at this and then we can merge.

Thank you!

2021-03-02 20:00 UTC, mikepapadim commented
Thanks! This should be ready now.

2021-03-03 06:25 UTC, jjfumero approved these changes

2021-03-03 06:26 UTC, merged