Fix dataflow analysis to retrieve data accesses
beehive-lab/TornadoVM pull request #96
Opened 2021-04-29 10:05 UTC by gigiblender

#### Description

This PR fixes the following:
- dataflow analysis to retrieve data accesses when not fully inlining.
- parameter load order in the callee when some of the parameters of the callee are not used.
- NPE in the scheduler when performing task migration with a CPU device.

I also included some cleanup of unused methods (`OCLCompilationResultsBuilder` and `OCLCompiler`)  and classes.

#### Problem description

In the Sketcher, Tornado runs a `TornadoDataflowAnalysis` phase that looks at the dataflow and assigns an `Access` for each parameter. Currently, we only analyze the method passed to the task, but not the non-inlined methods in the call graph. This can cause wrong accesses to be assigned to the parameters. Accesses of tasks are then used to generate nodes in the `TornadoGraph`.

With this PR, we merge the accesses of the caller with the accesses of the callees, obtaining the right accesses for the method.

#### Backend/s tested

- [X] OpenCL
- [X] PTX

#### OS tested

- [X] Linux
- [ ] OSx
- [ ] Windows

#### Did you check on FPGAs?

If possible, check your changes on FPGAs.

- [ ] Yes
- [X] No

#### How to test the new patch?

Run all the unit tests. 
`TestMultipleFunctions` should check for the task accesses and parameter order in non-inlined callees.

2021-04-30 06:40 UTC, jjfumero approved these changes

2021-05-05 12:52 UTC, stratika requested changes

2021-05-05 12:52 UTC, stratika commented on runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
> +     * Please note that this option experimental and may cause issues if enabled.
Add "is" -> Please note that this option is experimental and may cause issues if enabled.

2021-05-05 12:52 UTC, stratika commented on runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoSketchTierContext.java
> +     * Contains the argument accesses for this method. The array gets populated in the {@link TornadoDataflowAnalysis} phase.
Which method is the one referred as "this" method?

2021-05-05 12:52 UTC, stratika commented on tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/Access.java
> + * Enum used to specify the accesses of parameters passed on {@link uk.ac.manchester.tornado.api.common.TornadoFunctions.Task}
missing full stop at the end of line 45.

2021-05-05 12:52 UTC, stratika commented on unittests/src/main/java/uk/ac/manchester/tornado/unittests/tasks/TestMultipleFunctions.java
> + * Copyright (c) 2013-2021, APT Group, Department of Computer Science,
This is a new file, so the year should be 2021.

2021-05-06 07:25 UTC, stratika approved these changes

2021-05-06 07:36 UTC, merged